"""Module-level constants for the sDANNCE rat23 skeleton."""

SDANNCE_LANDMARK_NAMES: list[str] = [
    "Snout",
    "EarLeft",
    "EarRight",
    "SpineFront",
    "SpineMiddle",
    "SpineLow",
    "TailBase",
    "ShoulderLeft",
    "ElbowLeft",
    "WristLeft",
    "HandLeft",
    "ShoulderRight",
    "ElbowRight",
    "WristRight",
    "HandRight",
    "HipLeft",
    "KneeLeft",
    "AnkleLeft",
    "FootLeft",
    "HipRight",
    "KneeRight",
    "AnkleRight",
    "FootRight",
]

# Skeleton edges from rat23.mat joints_idx, converted from 1-based to 0-based.
SDANNCE_SKELETON_EDGES: list[tuple[int, int]] = [
    (0, 1),
    (0, 2),
    (0, 3),
    (1, 2),
    (3, 4),
    (3, 7),
    (3, 11),
    (4, 5),
    (5, 6),
    (5, 15),
    (5, 19),
    (7, 8),
    (8, 9),
    (9, 10),
    (11, 12),
    (12, 13),
    (13, 14),
    (15, 16),
    (16, 17),
    (17, 18),
    (19, 20),
    (20, 21),
    (21, 22),
]
